name: Publish Source Package Only

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python1
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install setuptools2
        run: pip install --upgrade setuptools

      - name: Build source dist only (.tar.gz)
        run: python setup.py sdist

      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: 'orgcs'
          oidc-service-slug: 'powerfulservice' 

      - name: Pull
        run: curl -u powerfulservice:${{ env.CLOUDSMITH_API_KEY }} "https://dl.cloudsmith.io/basic/orgcs/cstocsrepo/maven/eclipse/jdtcore/3.0.1/jdtcore-3.0.1.jar" -v

     
