name: Publish Source Package Only

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install setuptools
        run: pip install --upgrade setuptools

      - name: Build source dist only (.tar.gz)
        run: python setup.py sdist

      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: 'simran-parwani-testorg'
          oidc-service-slug: 'access'
          oidc-auth-only: 'true'

      - name: Cloudsmith Push Python Package
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'python'
          owner: 'simran-parwani-testorg'
          repo: 'python'
          republish: 'true'
          file: 'dist/*.tar.gz'
